### ISSUE TITLE
IndexError: list out of range 

### ISSUE THREAD

**Issue by Kata-Pa** [Kinggerm/GetOrganelle#14] opened 2019-06-21 20:31 UTC
Hello,

I just tried your tool, which looks quite useful, and everything runned fine until I got the following error:
File "/home/katerina87/miniconda3/bin/get_organelle_from_reads.py", line 3482, in main
    expected_maximum_size=options.expected_max_size[go_t],
IndexError: list index out of range

The command I run was 

get_organelle_from_reads.py -1 VM3-16_S1_R1.pick.fastq -2 VM3-16_S1_R2.pick.fastq -s Chloroplast.pick.fasta -o GetO_S1_assembly -F other_pt

The reference fasta I am using is from the same species.

Any help or hint on the error would be very helpful.
Thank you!

**Comment by Kinggerm** [comment] 2019-06-22 08:38
Sorry for the late reply and the inconvenience caused by this issue.
Please see https://github.com/Kinggerm/GetOrganelle/issues/13 for a temporary solution.
Alternatively, update to 1.6.2 (on the way).

Cheers!

**Comment by Kinggerm** [comment] 2019-06-22 17:42
1.6.2 released. You can use the removing dep way or update GetOrganelle to solve this problem.

**Comment by Kata-Pa** [comment] 2019-06-24 09:12
Ok will try the update, thank you for the fast reply :)

**Comment by Kata-Pa** [comment] 2019-06-24 12:20
So I updated but I still get the same error. I also noticed that the script is running from the bin in miniconda while I had done a pip3 install. I rerun using the script in my pip installed folder but still get the same error. So maybe conda and pip conflict is not the problem? Also deleted the ncbi-blast folder and reinstall, same error.
Could it be a problem of my input then?

**Comment by Kinggerm** [comment] 2019-06-24 12:26
Could be the conflict.
Can you show me the complete log file from which I can understand the environment you are using?
I don't think it's the problem with any of your input.

**Comment by Kata-Pa** [comment] 2019-06-24 12:31
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/3320788/get_org.log.txt)
 
Here it is

**Comment by Kinggerm** [comment] 2019-06-24 12:36
Sorry, my fault!!!! Eyes spent ...
It should not be the same issue with #13. I would look into this right now and get back to you soon.

**Comment by Kinggerm** [comment] 2019-06-24 12:49
Thank you very much for pointing out this bug! I got it. I missed the other_pt mode in few code lines and barely tested it. It is interesting that you are using GetOrganelle to assemble plastomes of non-embryophytes. 

Fixed now! Please update GetOrganelle, again. 
BTW, You can add "--continue" to the commands to quickly resume the previous run. Please let me know what you get.

**Comment by Kinggerm** [comment] 2019-06-24 12:57
It seems that you did not get many original reads but with extremely high pt percentage. Was it purified DNA or something?

**Comment by Kata-Pa** [comment] 2019-06-24 13:23
Thank you Jianjun!
I need to assemble the chloroplast of a diatom (phytoplankton). The genome is already known, so I mapped the raw reads and extracted only the ones matching to the chloroplast contig. Now will use your tool to assemble the chloroplast for the different strains I have. Hope it works nicely!
Thank you once more for your fast reply.

**Comment by Kinggerm** [comment] 2019-06-24 13:48
No problem!
You can do the mapping then use GetOrganelle if it is extremely close samples and the result says complete. However, to avoid incomplete result or bias, use GetOrganelle to assemble the plastome from the original reads would be much more preferred.

**Closed** 2019-06-24 13:53 UTC
