### ISSUE TITLE
Bowtie2 not found

### ISSUE THREAD

**Issue by ardy20** [Kinggerm/GetOrganelle#102] opened 2021-09-24 09:59 UTC
Dear Developer

I installed getOrganelle through conda. Howver, when I want to install get_organelle_config.py --add embplant_pt,embplant_mt

I get the error like Bowtie2 not found. I checked the bin folder in conda environment but the Bowtie2 is already there.

Could you please help to solve this problem?

Regards

**Comment by Kinggerm** [comment] 2021-09-24 14:48
This issue was caused by the crash of latest tbb on which bowtie relies. If you try the conda installed bowtie2, you will find errors. This issue was addressed here: https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#bowtie2-cannot-be-found, where you can find the solution.

Besides, I updated the conda recipe with tbb version downgraded, so that this problem can be averted ([see here](https://github.com/bioconda/bioconda-recipes/pull/29702)). However, something need to be down further to get the recipe passed, where I need help from those who is more familiar with bioconda.

**Comment by Kinggerm** [comment] 2021-10-14 19:29
If the issue was solved, I'm going to close this issue. Feel free to reopen it.

**Closed by Kinggerm** 2021-10-14 19:29 UTC
