### ISSUE TITLE
Processing with potentially contaminated data

### ISSUE THREAD

**Issue by ChenJuiYANG** [Kinggerm/GetOrganelle#72] opened 2021-04-14 07:47 UTC
After running `get_organelle_from_reads.py` for chloroplast genome assembly, I got a messy assembly graph. I thought it was failed at first. 

However, it seems the data was contaminated since the warning message by GetOrganelle when I try to assemble the nuclear ITS region. 

So, I re-examined the chloroplast genome assemble graph and use Bandage to remove those regions/nodes with low coverage (<~60x), as the demo video here provide. Finally, I yielded a typical assembly graph of chloroplast genome (with average coverage ~130x at SSC and LSC, and ~280x at IRs; in another case, remove <~30x nodes and yield ~75x at SSC and LSC, and ~176x at IRs).  

I have three questions here: 
1) Do these steps make sense? Could this result possibly be correct? 

2) Can I evaluate how correct are the assembled sequences I generated in GetOrganelle? or any suggested method/program? The blast results showed many mismatches on the edge of IRs with close-related species. Will that cause by incorrect assembly? 

3) Base on the graph, there are four different sequences/structures that I can generate. According to the FAQ here provided, only two isomeric sequences should be correct. The four structures indeed represent only two isomeric sequences, and the different sequences are produced by different cutting points and directions. Is this correct? 

BTW, I have tried to run again with close related species chloroplast genome as seeds, but the results was similar. 

Thanks a lot. 
--
BTW, I give up running this program on Windows system. The installation is too difficult for me. 
I currently use a public Mac in our lab. It's a bit slow though. 
Thanks for helping on the system issue anyway. :-)

**Comment by Kinggerm** [comment] 2021-04-14 13:53
Great to hear that you make it!

Please attach a log file and a png file of the assembly graph, so that I could help more.

Answers to your questions:

1. If the coverage differences are so clear and the graph is sufficient, above manual cleaning sounds reasonable. However, if the coverage are so clear and the graph is sufficient, GetOrganelle is usually robust to this kind of minor contamination, which it makes me more interested to see the log and the graph.
2. GetOrganelle has a tool in the utilities to evaluate called [evaluate_assembly_using_mapping.py](https://github.com/Kinggerm/GetOrganelle/blob/master/Utilities/evaluate_assembly_using_mapping.py) from one aspect. It's hard to say whether it's caused by incorrect assembly with current information.
3. If I understand you well, it's correct, those four sequences represent only two isomeric. Yeah, it's double-stranded circular DNA (say, in the sense of a single unit). You always have two strands and many cutting points.

BTW, I would suggest using semi-manual approaches than just using Bandage, e.g. if you want to remove contigs below 60x, after which there is no contamination left (confirmed in the Bandage), then type in 

    get_organelle_from_assembly.py --min-depth 60 --no-slim -g the_graph.gfa -o semi-manual-output

I believe getting the same result using different parameters/seeds is good news.

**Comment by ChenJuiYANG** [comment] 2021-04-15 02:40
Thanks for all the helps! 

I just realized that I opened a wrong file with "filtered_K127.assembly_graph.fastg.extend-embplant_pt-embplant_mt.fastg", rather than "embplant_pt.K127.complete.graph1.selected_graph.gfa". 

The .gfa file looks great, and the sequences that GetOrganelle produced are exactly the same with my processing steps! 

The .png file of the .fastg and log file are provided here anyway. There are 3 runs in the log file. 
![y887 messy_L](https://user-images.githubusercontent.com/81798914/114805678-fb05fa80-9dd5-11eb-95c6-4d64bf1ce8af.png)
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/6314837/get_org.log.txt)

Thanks again!!!

**Comment by Kinggerm** [comment] 2021-04-15 07:46
Congrats!
All these looks great. As the log file indicated, you have achieved successfully the complete chloroplast genome. Looking at the graph and the log file, I'm confident that it will be accurate and glad your manual processing have exactly the same result (I made mistakes with manual processing sometimes).

As for the nuclear ribosomal, it may not always because of the contamination, but may also due to the incomplete concerted evolution (also see [here](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#why-does-getorganelle-generate-a-circular-genome-for-embplant_nrfungus_nr))

I will close this issue since you have achieved the result successfully. Feel free to open it if you have any followups, or to open another.

**Closed by Kinggerm** 2021-04-15 07:46 UTC
