### ISSUE TITLE
Results- graph double mitochondria?

### ISSUE THREAD

**Issue by desmodus1984** [Kinggerm/GetOrganelle#77] opened 2021-04-27 23:01 UTC
Hi,

I am interesting in finding mtDNA functional annotation and I have used GetOrganelle to assemble mtgenome from NGS data, using original and error-corrected reads. I have a couple of questions, what is an organelle-sufficient graph? Could you please post what are good results based on graphs? I feel kinda confident with some results but with others I am sure that I am running into some issues which I do not know what is going on.

For example I know that the mitogenome has some repeats, so I should expect some loops in the assembly, like this:
![image](https://user-images.githubusercontent.com/40648021/116321416-02d77e80-a788-11eb-8485-f8e9f10a776b.png)

But my results keep getting weirder and weirder with more loops, like this:
![image](https://user-images.githubusercontent.com/40648021/116321627-69f53300-a788-11eb-84be-addcc929b46d.png)
I can share the log of this one later if you want.

The species I am studying in Myotis septentrionalis, with a mitogenome of ~17,362 , but the assemblies - I have several individuals is shorter: 1st one ; 16768, the weird one: 17030, and then this super weird with like a double different mitogenome - 
![image](https://user-images.githubusercontent.com/40648021/116322072-50a0b680-a789-11eb-9531-f033f473076a.png)

I blasted the big loops with ~64X and 42X coverage and the 42X mapped to my species, with the 64X mapped to a very different one.
[Pa90.get_org.log](https://github.com/Kinggerm/GetOrganelle/files/6388113/Pa90.get_org.log)

What can I do to recover the genome of my species of interest? and even, is there a way to split them to recover the genome of the other?

I have attached the report in case there is any useful information for suggestions.

Thanks;

**Comment by Kinggerm** [comment] 2021-04-28 05:53
All those should be organelle-sufficient graphs. All those results with a complete genome from [here](https://github.com/Kinggerm/GetOrganelleComparison/tree/master/res/GetOrganelle-animal-mitogenome) should be organelle-sufficient, although some incomplete results may have organelle-sufficient graph too. 

Did GetOrganelle generate the complete circular genome for the first two graphs? It may be failed/crashed due to the extremely high coverage (therefor high copy number) of the repeats. If it failed, you may follow the manual completion [here](https://www.youtube.com/watch?v=cXUV7k-F26w), but the copy numbers has to be estimated by your self. I'm working on improving the copy number estimation function, which will be released in another tool first though.

The third graph is very interesting. I've observed similar situation in some public data. This should be a combination of two mitogenome from two related species. This could be cause by either contamination (usually the coverage will be very uneven), or the a hybrid individual gaining mitogenomes from both parents (just from my guess). You may use blast to identify each parallel contig pairs (e.g. 64.4x vs 42.4x; green vs purple in the middle), duplicate shared contigs, and manually separate those contigs into to graph conponents (circles).

Let me know what you get~

**Comment by desmodus1984** [comment] 2021-04-29 19:48
Hi @Kinggerm 
YOu mentioned that contamination will lead to an uneven coverage, so would you say that what I found is uneven? I feel that they are kit even, though some areas are not.

I wanted to ask you another question. I have 100bp PE-reads, which are the optimal k-mer sizes for me to use?
I basically eliminated the one in the example which was higher than 100 and I have been using 21,45,65,85. Also, for some individuals the filtered assembly was 65 while for others it is 85, does it say something about coverage, quality of data, that I should pay attention and change the parameters?
Normally, I have ~ 20 GBs or more for each individual.

Thanks;

**Comment by Omunity** [comment] 2021-04-30 02:36
It's quite even in this case. Contamination would **USUALLY** have much lower coverage. You would know the data better than I do, e.g. potential contaminating species or other related biological influences. 

Please check the [Instruction](https://github.com/Kinggerm/GetOrganelle#instruction) for k-mer choices. I would not pay too much attention on the k-mer, but use a gradient values instead. GetOrganelle will benefit from the gradient values (check our manuscript for a more detailed discussion).

Based on both the graph and the >20 GBs info, I believe you have enough data for each individual.

**Comment by Kinggerm** [comment] 2021-04-30 02:39
It's quite even in this case. Contamination would USUALLY have much lower coverage. In this sense, fig3 is less likely to be caused by contamination. You would know the data better than I do, e.g. other related biological influences.

Please check the Instruction for k-mer choices. I would not pay too much attention on the k-mer, but use a gradient values instead. GetOrganelle will benefit from the gradient values (check our manuscript for a more detailed discussion).

Based on both the graph and the >20 GBs info, I believe you have enough data for each individual.

**Closed** 2022-01-12 01:47 UTC
